# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_email',
        ),
        migrations.AddField(
            model_name='client',
            name='client_date',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='client_description',
            field=models.TextField(default='none', max_length=800),
        ),
    ]
