# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-18 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='audit_done',
            field=models.BooleanField(default=False),
        ),
    ]
