# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-27 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_client_audit_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='review_done',
            field=models.BooleanField(default=False),
        ),
    ]
