# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20200616_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_date',
            field=models.DateField(default='0'),
        ),
    ]
