# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('feature1', models.CharField(blank=True, max_length=100)),
                ('feature2', models.CharField(blank=True, max_length=100)),
                ('feature3', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('most_popular', models.BooleanField(default=False)),
                ('pages_audited', models.FloatField()),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
