# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-01 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], max_length=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
