# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-07 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20200702_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_description',
            field=models.TextField(max_length=120),
        ),
    ]
